"""

    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Django settings for xrhms project.

    Generated by 'django-admin startproject' using Django 2.2.6.

    For more information on this file, see
    https://docs.djangoproject.com/en/2.2/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

#Add prefix on so it works on production server

URL_PREFIX = "/xrhms"
FORCE_SCRIPT_NAME = URL_PREFIX
SESSION_COOKIE_PATH = "/xrhms"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_ROOT = os.path.join(BASE_DIR, "static")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SOMETHING SECRET HERE'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["xrh-server.soton.ac.uk"]
DEFAULT_FROM_EMAIL = "xrh@soton.ac.uk"


SUPER_USER_ID = 1 # The ID of the user to assign things to if not defined elsewhere
# Application definition

INSTALLED_APPS = [
    'django_mysql',
    'polymorphic',
    'labels.apps.LabelsConfig',
    'samples.apps.SamplesConfig',
    'scans.apps.ScansConfig',
    'projects.apps.ProjectsConfig',
    'muvis.apps.MuvisConfig',
    'user_profile.apps.UserProfileConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'private_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xrhms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xrhms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR,"mysql.cnf")
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

from .dev_settings import * #pylint: disable=unused-wildcard-import, wildcard-import

#STATIC_URL = '/static/'
STATIC_URL= "{}/static/".format(URL_PREFIX)

#Private files configuration
PRIVATE_STORAGE_ROOT = '/mnt/xrh-general/xrhms'
PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_staff'
FILE_UPLOAD_PERMISSIONS = 0o640
VIDEO_TYPES = [
]

ATTACHMENT_TYPES = [
    "application/gzip",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.visio",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/pdf",
    "application/zip",
    "application/x-7z-compressed",
    "image/bmp",
    "image/jpeg",
    "image/png",
    "image/tiff",
    "image/svg+xml",
    "video/x-msvideo", # It's not a format playable in a browser so don't count it as a video
    "video/mpeg", # Also not previewable
    "video/avi",
    "video/mp4",
]
ATTACHMENT_TYPES += VIDEO_TYPES

ATTACHMENT_FILE_SIZE_LIMIT=600*1024*1024
LARGE_ATTACHMENT_FILE_SIZE_LIMIT=1024*1024*1024*3

USER_DATA_FOLDER = "/mnt/xrh-users"
CREATE_FOLDER_SCRIPT = "/opt/xrhms-venv/xrhms/create_user_folder.py"
DEFAULT_USER_COPY_DELETION_DAYS = 30

USER_COPY_SCAN_README = "static/SCAN_README.txt"

EXTRA_FOLDER = "extra"
VIDEO_FOLDER = "videos"

SCAN_VIDEO_EXTENSION = [
    "mp4",
]

#constants used for transfer time tables expressed in Bytes/second
TRANSFER_SPEED_1GBIT = 1024 * 1024 * 1024 /8
TRANSFER_SPEED_USB2 = 480 * 1024 *1024 /8
TRANSFER_SPEED_USB3 = 4.8 * 1024 * 1024 * 1024 / 8

SAMPLE_INFO_FILE = "SAMPLE_INFO.txt"
