# Generated by Django 2.2.10 on 2020-02-25 12:05
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0020_auto_20200224_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikonctscan',
            name='beam_hardening_lut_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beam hardening LUT file'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='detector_offset_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Detector offset X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='detector_offset_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Detector offset Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='detector_pixel_size_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Detector pixel size X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='detector_pixel_size_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Detector pixel size Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='detector_pixels_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Detector pixels X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='detector_pixels_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Detector pixels Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='offset_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Offset X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='offset_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Offset Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='offset_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Offset Z'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='region_pixels_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Region pixels X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='region_pixels_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Region pixels Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='region_start_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Region start X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='region_start_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Region start Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='voxel_size_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Voxel size X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='voxel_size_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Voxel size Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='voxel_size_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Voxel size Z'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='voxels_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Voxels X'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='voxels_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Voxels Y'),
        ),
        migrations.AlterField(
            model_name='nikonctscan',
            name='voxels_z',
            field=models.IntegerField(blank=True, null=True, verbose_name='Voxels Z'),
        ),
    ]
