# Generated by Django 2.2.11 on 2020-05-05 15:10
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations

from scans.models import ScanAttachmentType

class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0047_scanattachmenttype_report_priority'),
    ]

    def insert_attachment_types(apps, schema_editor):
        types = [
            ("Thick slice MIP", "A Maximum Intensity Projection (MIP) of the sample through the Histologically relevent plane.", 40),
            ("Thick slice Sum", "A sum of the pixels of multiple slices through the Histologically relevent plane.", 60),
            ("3D MIP spin", "A 3D rotation of a Maximum Intentity Projection (MIP)", 70)
        ]

        for i in types:
            if ScanAttachmentType.objects.filter(name=i[0]).count() == 0:
                t = ScanAttachmentType(name=i[0], description=i[1], report_priority=i[2])
                t.save()

    def rename_attachment_types(apps, schema_editor):
        t = ScanAttachmentType.objects.get(name="Single slice video (X)")
        t.name = "YZ Slice roll"
        t.report_priority = 30
        t.save()
        t = ScanAttachmentType.objects.get(name="Single slice video (Y)")
        t.name = "XZ Slice roll"
        t.report_priority = 20
        t.save()
        t = ScanAttachmentType.objects.get(name="Single slice video (Z)")
        t.name = "XY Slice roll"
        t.report_priority = 10
        t.save()
        t = ScanAttachmentType.objects.get(name="Raw radiograph video")
        t.name = "X-Ray 360 spin"
        t.report_priority = 90
        t.save()
        t = ScanAttachmentType.objects.get(name="Thick slice video (Z)")
        t.name = "Thick slice Avg"
        t.description = "An average intensity projection of thesample through the Histologically relevent plane."
        t.report_priority = 50
        t.save()
        t = ScanAttachmentType.objects.get(name="Rotation video")
        t.name = "3D Volume spin"
        t.report_priority = 80
        t.save()

    operations = [
        migrations.RunPython(insert_attachment_types),
        migrations.RunPython(rename_attachment_types)
    ]
