# Generated by Django 2.2.13 on 2020-06-18 10:01
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0064_auto_20200610_1242'),
    ]

    operations = [

        migrations.AddField(
            model_name='scan',
            name='tdetector_pixel_size_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Detector pixel size X'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tdetector_pixel_size_x = t2.detector_pixel_size_x"),


        migrations.RemoveField(
            model_name='nikonctscan',
            name='detector_pixel_size_x',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tdetector_pixel_size_x',
            new_name='detector_pixel_size_x'
        ),


        migrations.AddField(
            model_name='scan',
            name='tdetector_pixel_size_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Detector pixel size Y'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tdetector_pixel_size_y = t2.detector_pixel_size_y"),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_dectrisctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tdetector_pixel_size_y = t2.detector_pixel_size_y"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='detector_pixel_size_y',
        ),

        migrations.RenameField(
            model_name='scan',
            old_name='tdetector_pixel_size_y',
            new_name='detector_pixel_size_y'
        ),


        migrations.AddField(
            model_name='scan',
            name='tdetector_pixels_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Detector pixels Y'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tdetector_pixels_y = t2.detector_pixels_y"),
 
        migrations.RemoveField(
            model_name='nikonctscan',
            name='detector_pixels_y',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tdetector_pixels_y',
            new_name='detector_pixels_y'
        ),

        migrations.AddField(
            model_name='scan',
            name='tdetector_pixels_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Detector pixels X'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tdetector_pixels_x = t2.detector_pixels_x"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='detector_pixels_x',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tdetector_pixels_x',
            new_name='detector_pixels_x'
        ),
        
        migrations.AddField(
            model_name='scan',
            name='tinitial_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tinitial_angle = t2.initial_angle"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='initial_angle',
        ),

        migrations.RenameField(
            model_name='scan',
            old_name='tinitial_angle',
            new_name='initial_angle'
        ),
        
        
        migrations.AddField(
            model_name='scan',
            name='tprojections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tprojections = t2.projections"),

        migrations.RemoveField(
            model_name='nikonctscan',
            name='projections',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tprojections',
            new_name='projections'
        ),
        
        migrations.AddField(
            model_name='scan',
            name='tframes_per_projection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tframes_per_projection = t2.frames_per_projection"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='frames_per_projection',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tframes_per_projection',
            new_name='frames_per_projection'
        ),
        
        migrations.AddField(
            model_name='scan',
            name='tsrc_to_detector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tsrc_to_detector = t2.src_to_detector"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='src_to_detector',
        ),

        migrations.RenameField(
            model_name='scan',
            old_name='tsrc_to_detector',
            new_name='src_to_detector'
        ),
        
        
        migrations.AddField(
            model_name='scan',
            name='tsrc_to_object',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tsrc_to_object = t2.src_to_object"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='src_to_object',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tsrc_to_object',
            new_name='src_to_object'
        ),
        
        migrations.AddField(
            model_name='scan',
            name='txray_kv',
            field=models.IntegerField(blank=True, null=True, verbose_name='X-Ray Voltage (kV)'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.txray_kv = t2.xray_kv"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='xray_kv',
        ),

        migrations.RenameField(
            model_name='scan',
            old_name='txray_kv',
            new_name='xray_kv'
        ),
        
        migrations.AddField(
            model_name='scan',
            name='txray_ua',
            field=models.IntegerField(blank=True, null=True, verbose_name='X-Ray Current (µA)'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.txray_ua = t2.xray_ua"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='xray_ua',
        ),
       
        migrations.RenameField(
            model_name='scan',
            old_name='txray_ua',
            new_name='xray_ua'
        ),
        
        
        migrations.AddField(
            model_name='scan',
            name='tprojection0deg',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Attachment'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tprojection0deg = t2.projection0deg"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='projection0deg',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tprojection0deg',
            new_name='projection0deg'
        ),
        
        migrations.AddField(
            model_name='scan',
            name='tprojection0deg_png',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Attachment'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tprojection0deg_png = t2.projection0deg_png"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='projection0deg_png',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tprojection0deg_png',
            new_name='projection0deg_png'
        ),
       

        migrations.AddField(
            model_name='scan',
            name='tprojection90deg',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Attachment'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tprojection90deg = t2.projection90deg"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='projection90deg',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tprojection90deg',
            new_name='projection90deg'
        ),

        migrations.AddField(
            model_name='scan',
            name='tprojection90deg_png',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Attachment'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.tprojection90deg_png = t2.projection90deg_png"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='projection90deg_png',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='tprojection90deg_png',
            new_name='projection90deg_png'
        ),

        migrations.AddField(
            model_name='scan',
            name='txyslice',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Attachment'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.txyslice = t2.xyslice"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='xyslice',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='txyslice',
            new_name='xyslice'
        ),
            
        migrations.AddField(
            model_name='scan',
            name='txyslice_png',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Attachment'),
        ),
        migrations.RunSQL("UPDATE scans_scan AS t1 INNER JOIN scans_nikonctscan AS t2 on t1.id = t2.scan_ptr_id SET t1.txyslice_png = t2.xyslice_png"),
        migrations.RemoveField(
            model_name='nikonctscan',
            name='xyslice_png',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='txyslice_png',
            new_name='xyslice_png'
        ),
    ]
