# Generated by Django 2.2.13 on 2020-09-09 16:18
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations
from django.utils import timezone
from scans.models import Scan
from scans.models.dataset_status import DATASET_MISSING
class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0081_auto_20200909_1617'),
    ]

    def update_dataset_status(apps, schema_editor):
        missing = Scan.objects.filter(file_exists=0)
        for scan in missing:
            scan.dataset_status = DATASET_MISSING
            scan.dataset_status_last_updated = timezone.now()
            scan.save()
    operations = [
        migrations.RunPython(update_dataset_status),
    ]
