# Generated by Django 2.2.13 on 2020-09-30 10:54
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0092_auto_20200917_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the channel', max_length=40, unique=True)),
                ('emmission_wavelength', models.FloatField(help_text='The frequency  of the light source (nm)', unique=True)),
                ('samples_per_pixel', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OmeObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_na', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(db_index=True, max_length=30)),
                ('nominal_magnification', models.FloatField(blank=True, null=True)),
                ('working_distance', models.FloatField(blank=True, help_text='Working distance in µm', null=True)),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
        migrations.CreateModel(
            name='OmePlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure', models.FloatField(blank=True, help_text='exposure time (s)', null=True)),
                ('position_x', models.FloatField(blank=True, help_text='X position in µm', null=True)),
                ('position_y', models.FloatField(blank=True, help_text='Y position in µm', null=True)),
                ('binning', models.CharField(blank=True, help_text='Was the detector binned for acquisition', max_length=5, null=True)),
                ('t', models.IntegerField(blank=True, help_text='Time interval for image', null=True)),
                ('z', models.IntegerField(blank=True, help_text='Z position', null=True)),
                ('channel', models.ForeignKey(blank=True, help_text='The channel used for illumination', null=True, on_delete=django.db.models.deletion.PROTECT, to='scans.OmeChannel')),
            ],
        ),
        migrations.CreateModel(
            name='OmeData',
            fields=[
                ('scan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scans.Scan')),
                ('acquisition_date', models.DateTimeField(db_index=True)),
                ('pixels_big_endian', models.BooleanField(blank=True, null=True)),
                ('pixels_dimension_order', models.CharField(blank=True, max_length=12, null=True)),
                ('pixels_interleaved', models.BooleanField(blank=True, null=True)),
                ('pixels_significant_bits', models.IntegerField(blank=True, null=True)),
                ('pixels_type', models.CharField(blank=True, max_length=10, null=True)),
                ('physical_size_x', models.FloatField(blank=True, help_text='X dimension in µm', null=True)),
                ('physical_sixe_y', models.FloatField(blank=True, help_text='Y dimension in µm', null=True)),
                ('pixels_x', models.IntegerField(blank=True, null=True)),
                ('pixels_y', models.IntegerField(blank=True, null=True)),
                ('size_c', models.IntegerField(blank=True, null=True)),
                ('size_z', models.IntegerField(blank=True, null=True)),
                ('size_t', models.IntegerField(blank=True, null=True)),
                ('refractive_index', models.FloatField(blank=True, null=True)),
                ('preview', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Preview')),
                ('overview', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='scan', verbose_name='Overview')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scans.OmeObjective')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('scans.scan',),
        ),
    ]
