# Generated by Django 2.2.13 on 2020-12-18 16:09
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0118_auto_20201123_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_recon_data', models.BooleanField(default=True, help_text='Copy the reconstructed data folder')),
                ('include_raw_data', models.BooleanField(default=False, help_text='Copy the raw projections')),
                ('username', models.CharField(help_text='The user to make the files available to', max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_copied', models.DateTimeField(blank=True, help_text='When the data was copied to the user store', null=True)),
                ('copy_success', models.BooleanField(blank=True, db_index=True, null=True)),
                ('deletion_after', models.IntegerField(default=30, help_text='How many days to leave available for (minimum)')),
                ('cmd_output', models.TextField(blank=True, help_text='Output from the various commands', null=True)),
                ('date_deleted', models.DateTimeField(help_text='When the files were removed', null=True)),
                ('deletion_sucess', models.BooleanField(blank=True, db_index=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scans.Scan')),
            ],
            options={
                'verbose_name_plural': 'User Copies',
                'unique_together': {('scan', 'username', 'date_added')},
            },
        ),
    ]
