# Generated by Django 2.2.17 on 2021-02-22 17:49
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations
from scans.models import ScanAttachmentType, ScanAttachmentTypeSuffix

class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0129_auto_20210222_1746'),
    ]

    def add_minInt(apps, schema_editor):
        minint = ScanAttachmentType(name="Thick Slice MinIP", report_priority=45)
        minint.save()

    def add_suffixes(apps, schema_editor):
        pairings = [
            ("XY Slice Roll", "_XYSliceRoll"),
            ("YZ Slice Roll", "_YZSliceRoll"),
            ("XZ Slice Roll", "_XZSliceRoll"),
            ("Thick Slice Avg", "AvgInt"),
            ("Thick Slice MIP", "MaxInt"),
            ("Thick Slice StDev", "StDev"),
            ("Thick Slice MinIP", "MinInt_"),
        ]
        for (atype, suffix) in pairings:
            suffix_obj = ScanAttachmentTypeSuffix()
            suffix_obj.attachment_type = ScanAttachmentType.objects.get(name=atype)
            suffix_obj.suffix = suffix
            suffix_obj.save()

    operations = [
        migrations.RunPython(add_minInt),
        migrations.RunPython(add_suffixes)
    ]
