# Generated by Django 2.2.6 on 2019-10-29 11:36
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0015_auto_20191028_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the location', max_length=50, unique=True)),
                ('location', models.CharField(help_text='The actual location of the place. eg SGH/LA68', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='More details about the location')),
            ],
        ),
        migrations.CreateModel(
            name='SampleLocationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('location', models.ForeignKey(help_text='Where the sample is moved to', on_delete=django.db.models.deletion.PROTECT, to='samples.Location')),
                ('sample', models.ForeignKey(help_text='The sample this status refers to', on_delete=django.db.models.deletion.PROTECT, to='samples.Sample')),
                ('user', models.ForeignKey(blank=True, help_text='The user who made the change', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='By')),
            ],
        ),
    ]
