# Generated by Django 2.2.10 on 2020-03-11 17:26
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations
from samples.models import SampleIdPrefix

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0050_auto_20200302_1607'),
    ]

    def insert_sample_prefixes(app, schema_editor):
        prefixes = [
            ("CMCF", "Commerical confidential. This data is not to be index or used by us at all. To be archived to muvis systems ONLY."),
            ("XTAC", "External academic. These samples are provided by an external organisation and while we can index the data & metadata addtional permission is needed for our use. The intention is that the data will be published by the collaborator."),
            ("SXAA", "Southampton XRH Histology default prefix"),
            ("DEMO", "Samples that are used for training or demo purposes, such as the mince pie / kinder egg.")
        ]

        for i in prefixes:
            if SampleIdPrefix.objects.filter(prefix=i[0]).count() == 0:
                p = SampleIdPrefix(prefix=i[0], description=i[1])
                p.save()

    operations = [
        migrations.RunPython(insert_sample_prefixes)
    ]
