# Generated by Django 2.2.13 on 2020-07-08 10:18
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations
from samples.models import SampleAttachmentType

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0078_merge_20200618_0959'),
    ]

    def rearrange_photos(app, schema_editor):
        t = SampleAttachmentType.objects.get(name="Delivered Photo")
        t.name = "Delivered photo front"
        t.description = "Photo of the front of the sample as delivered"
        t.save()
        t = SampleAttachmentType.objects.get(name="Returned Photo")
        t.name = "Returned photo front"
        t.description = "Photo of the front of the sample as returned"
        t.save()
        t = SampleAttachmentType(
            name="Delivered photo back",
            description="Photo of the back of the sample as delivered")
        t.save()
        t = SampleAttachmentType(
            name="Returned photo back",
            description="Photo of the back of the sample as returned")
        t.save()
        t = SampleAttachmentType(
            name="Generic photo",
            description="Generic photo of the sample or sample setup")
        t.save()

    operations = [
        migrations.RunPython(rearrange_photos)
    ]
