# Generated by Django 2.2.20 on 2021-05-24 09:04
"""
    Copyright 2023 University of Southampton
    Dr Philip Basford
    μ-VIS X-Ray Imaging Centre

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0094_auto_20210304_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(help_text='The type of the sample. Once created this CANNOT be easily changed.', on_delete=django.db.models.deletion.PROTECT, to='samples.SampleType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='species',
            field=models.ForeignKey(help_text='What species is the sample from. Once created this CANNOT be easily changed.', on_delete=django.db.models.deletion.PROTECT, to='samples.Species'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tissue',
            field=models.ForeignKey(help_text='The tissue that the sample is of. Once created this CANNOT be easily changed.', on_delete=django.db.models.deletion.PROTECT, to='samples.Tissue'),
        ),
    ]
